import 'package:tech_test/%20model/results_model.dart';

class Autogenerated {
  Results? results;

  Autogenerated({this.results});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    results =
        (json['results'] != null ? Results.fromJson(json['results']) : null)!;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results!.toJson();
    }
    return data;
  }
}
