import 'dart:convert';
import 'package:dio/dio.dart';
import 'package:tech_test/%20model/album_model.dart';
import 'package:tech_test/%20model/root_model.dart';

class AlbumViewModel {
  List<Album> albums = [];

  Future<List<Album>> fetchAlbums(String query) async {
    albums = []; //clear previous search

    var url =
        "https://ws.audioscrobbler.com/2.0/?method=album.search&album=$query&api_key=0ecf4edece2e46d68a0c5a01c0585892&format=json";
    Response response = await Dio().get(url);

    if (response.statusCode == 200) {
      Autogenerated autogenerated = Autogenerated.fromJson(
          jsonDecode(jsonEncode(response.data))); // Load JSON into class
      autogenerated.results?.albummatches?.album?.forEach((album) {
        albums.add(album);
      });
      return albums;
    }
    throw Exception("Error retrieving albums");
  }
}
